### ISSUE TITLE
Fatal error C1083: Cannot open include file: 'Sprite.hpp': No such file or directory

### ISSUE THREAD

**Issue by cobbyroddie** [BastiaanOlij/gdnative_cpp_example#14]
When I try to execute the command "scons platform=windows generate_bindings=yes" on the native tools command prompt for VS, I get the following error:
fatal error C1083: Cannot open include file: 'Sprite.hpp': No such file or directory
scons: *** [src\gdexample.obj] Error 2
scons: building terminated because of errors.

My SConstruct source code looks like the following:

#!python
import os, subprocess

opts = Variables([], ARGUMENTS)

 Gets the standard flags CC, CCX, etc.
env = DefaultEnvironment()

Define our options
opts.Add(EnumVariable('target', "Compilation target", 'debug', ['d', 'debug', 'r', 'release']))
opts.Add(EnumVariable('platform', "Compilation platform", '', ['', 'windows', 'x11', 'linux', 'osx']))
opts.Add(EnumVariable('p', "Compilation target, alias for 'platform'", '', ['', 'windows', 'x11', 'linux', 'osx']))
opts.Add(BoolVariable('use_llvm', "Use the LLVM / Clang compiler", 'no'))
opts.Add(PathVariable('target_path', 'The path where the lib is installed.', 'demo/bin/'))
opts.Add(PathVariable('target_name', 'The library name.', 'libgdexample', PathVariable.PathAccept))

Local dependency paths, adapt them to your setup
godot_headers_path = "../godot-cpp/godot-headers/"
cpp_bindings_path = "../godot-cpp/"
cpp_library = "libgodot-cpp"

only support 64 at this time..
bits = 64

Updates the environment with the option variables.
opts.Update(env)

Process some arguments
if env['use_llvm']:
    env['CC'] = 'clang'
    env['CXX'] = 'clang++'

if env['p'] != '':
    env['platform'] = env['p']

if env['platform'] == '':
    print("No valid target platform selected.")
    quit();

Check our platform specifics
if env['platform'] == "osx":
    env['target_path'] += 'osx/'
    cpp_library += '.osx'
    if env['target'] in ('debug', 'd'):
        env.Append(CCFLAGS = ['-g','-O2', '-arch', 'x86_64', '-std=c++17'])
        env.Append(LINKFLAGS = ['-arch', 'x86_64'])
    else:
        env.Append(CCFLAGS = ['-g','-O3', '-arch', 'x86_64', '-std=c++17'])
        env.Append(LINKFLAGS = ['-arch', 'x86_64'])

elif env['platform'] in ('x11', 'linux'):
    env['target_path'] += 'x11/'
    cpp_library += '.linux'
    if env['target'] in ('debug', 'd'):
        env.Append(CCFLAGS = ['-fPIC', '-g3','-Og', '-std=c++17'])
    else:
        env.Append(CCFLAGS = ['-fPIC', '-g','-O3', '-std=c++17'])

elif env['platform'] == "windows":
    env['target_path'] += 'win64/'
    cpp_library += '.windows'

    This makes sure to keep the session environment variables on windows,
    that way you can run scons in a vs 2017 prompt and it will find all the required tools
    env.Append(ENV = os.environ)

    env.Append(CCFLAGS = ['-DWIN32', '-D_WIN32', '-D_WINDOWS', '-W3', '-GR', '-D_CRT_SECURE_NO_WARNINGS'])
    if env['target'] in ('debug', 'd'):
        env.Append(CCFLAGS = ['-EHsc', '-D_DEBUG', '-MDd'])
    else:
        env.Append(CCFLAGS = ['-O2', '-EHsc', '-DNDEBUG', '-MD'])

if env['target'] in ('debug', 'd'):
    cpp_library += '.debug'
else:
    cpp_library += '.release'

cpp_library += '.' + str(bits)

make sure our binding library is properly includes
env.Append(CPPPATH=['.', godot_headers_path, cpp_bindings_path + 'include/', cpp_bindings_path + 'include/core/', cpp_bindings_path + 'include/gen/'])
env.Append(LIBPATH=[cpp_bindings_path + 'bin/'])
env.Append(LIBS=[cpp_library])

tweak this if you want to use different folders, or more folders, to store your source code in.
env.Append(CPPPATH=['src/'])
sources = Glob('src/*.cpp')

library = env.SharedLibrary(target=env['target_path'] + env['target_name'] , source=sources)

Default(library)

Generates help for the -h scons option.
Help(opts.GenerateHelpText(env))

I have made sure that there were no spelling discrepancies between the godot header file name and the one in the SConstruct source code, as they both are: godot-headers.

I have also copied the godot.hpp - which I found in the godot-cpp repository file in the following directory: C:\...\godot-cpp\include\godot-cpp - file and pasted it in the godot_headers folder, which seems to have solved the anterior error:  Fatal error C1083: Cannot open include file: 'Godot.hpp': No such file or directory

I tried to look for a sprite.hpp file in the example's folder but to no avail, I am wondering whether it got deleted by mistake, but I rechecked the example's folder on Github multiple times and found no trace of it. Is it even needed? If not, why do I get the aforementioned error?

**Comment by BastiaanOlij** [comment]
You have to run that on the `godot-cpp` library first, then you can compile your library. 
It is when you compile `godot-cpp` that `generate_bindings=yes` generates the binaries including the `sprite.hpp` file.
